### ISSUE TITLE
Access to the dataset

### ISSUE THREAD

**Issue by saikrishnarallabandi** [cyrta/broadcast-news-videos-dataset#2]
Hi,

Thanks for creating the dataset! And very nice explanation of the interesting work too. Can you provide a pointer to the database?

**Comment by cyrta** [comment]
Data are being clean and verified again. There are going to be available on this repo around start of December.

**Comment by saikrishnarallabandi** [comment]
Hi,

Any update on this. Thanks!

**Comment by francoishernandez** [comment]
Hi @cyrta , are you still planning to release the dataset?
Thanks!
